### ISSUE TITLE
garden install --app flag installs in libs/garden/garden.[pkg]

### ISSUE THREAD

**Issue by MelleB** [kivy-garden/garden#14]
If you install a garden package in your app it installed in libs/garden/garden.[pkg] directory, which makes it impossible to import.

E.g. `garden install --app filebrowser` installs the filebrowser in libs/garden/garden.filebrowser

Is this a bug or by design?
If it's a bug, I'd be willing to fix it.

Kivy 1.9.1
OS: Windows 7

**Comment by KeyWeeUsr** [comment]
It's an intended behavior and you can import the package with this:

    from kivy.garden.[pkg] import Class

see [kivy/kivy/garden](https://github.com/kivy/kivy/blob/master/kivy/garden/__init__.py#L80) for more.
