### ISSUE TITLE
garden install fails

### ISSUE THREAD

**Issue by tealc210** [kivy-garden/garden#33]
Hi,

Since last commit, I can't install anymore :

Traceback (most recent call last):
  File "/home/kivy/venv/bin/garden", line 189, in <module>
    GardenTool().main(sys.argv[1:])
  File "/home/kivy/venv/bin/garden", line 71, in main
    options.func()
  File "/home/kivy/venv/bin/garden", line 109, in cmd_install
    fd = self.download(opts.package)
  File "/home/kivy/venv/bin/garden", line 170, in download
    data += buf
TypeError: Can't convert 'bytes' object to str implicitly

Plus 'pip list' shows Kivy-Garden in version 0.1.1

But if I use garden from previous commit (2017-07-21), everything is OK (trying to install mapview).

**Comment by tealc210** [comment]
It was in fact a coincidence, the "problem" was that I needed to update the Buildozer (1st time using it) recipe for Garden with a newer version.

**Comment by rods-rodolfo** [comment]
i'm having the same error. how do you update buildozer recipe for garden ?

**Comment by AndreMiras** [comment]
Garden is deprecated, come to Discord for support
