### ISSUE TITLE
Cannot run Garden install "package" on Windows 10

### ISSUE THREAD

**Issue by Fionnoch** [kivy-garden/garden#37]
I have tried several times to install kivy garden packages using garden install "package" however I keep getting the following issue: 

D:\path to venv>python.exe D:\path to venv\Scripts\garden install matplotlib
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\python.exe: can't open file 'D:\Users\Fionn': [Errno 2] No such file or directory

I suspect the issue is potentially due to a space in my path however I won't be able to create a work around to this. I have tried adding garden to the path however I may not have added the correct folder to the path. 

What I was hoping to do was to copy the files directly from github to the correct location however I am not sure how that could be done. 

Any assistance would be hugely appreciated!

**Comment by matham** [comment]
The command is simply `garden install matplotlib`, not `python garden install matplotlib`

**Comment by Fionnoch** [comment]
Hi @matham, 

That is the command I entered however the problem isn't relating to garden not being able to install the library its related to not being able to use garden at all.

**Comment by Fionnoch** [comment]
> The command is simply `garden install matplotlib`, not `python garden install matplotlib`

Hi @matham,

That is the command I entered however the problem isn't relating to garden not being able to install the library its related to not being able to use garden at all.
