### ISSUE TITLE
garden.bat is missing "" to take into account blanks in folder names

### ISSUE THREAD

**Issue by sdementen** [kivy-garden/garden#9]
quotes should be added in garden.bat to be

    python.exe "%~dp0garden" %*

instead of

    python.exe %~dp0garden %*

**Comment by KeyWeeUsr** [comment]
Fixed with #20 Hehe, didn't even see this issue.

**Comment by matham** [comment]
Fixed by https://github.com/kivy-garden/garden/pull/20.

**Comment by jxoesneon** [comment]
I have this issue on the latest version from pip
